baseURL = "http://example.org/"
languageCode = "en-us"
title = "Oscuro Quintet"
theme = "oscuro"

[[menu.main]]
weight = 1
name = "About"
url = "/about"

[[menu.main]]
weight = 2
name = "Events"
url = "/events"

[[menu.main]]
weight = 3
name = "Media"
url = "/events"

[[menu.main]]
weight = 4
name = "Contact"
url = "/contact"

# params
[params]
date_format = "Monday, January 2, 2006"
copyright = "Copyright (c) 2018, Linode LLC"
logo = "/img/linode-logo_standard_light_small.png"

[params.truncate]
enable = true

[params.topbar]
enable = true
text = "For Developers, By Developers"

[params.carousel]
enable = true

[params.features]
enable = true

[params.features2]
enable = true

[params.dev]
enable = false